Update advance-trait.md
sunface/rust-course pull request #225
Opened 2022-01-17 08:56 UTC by JesseAtSZ

2022-01-17 14:23 UTC, Sefank reviewed
提供了一些参考和建议~

2022-01-17 14:23 UTC, Sefank commented on book/contents/basic/trait/advance-trait.md
> +就像人类妈妈会给自己的宝宝起爱称一样，狗妈妈也会。狗妈妈称呼自己的宝宝为**Spot**，其它动物称呼狗宝宝为**puppy**，这个时候假如有动物，不知道该称如何呼狗宝宝，它需要查询一下。
感觉这里不需要逗号~
```suggestion
就像人类妈妈会给自己的宝宝起爱称一样，狗妈妈也会。狗妈妈称呼自己的宝宝为**Spot**，其它动物称呼狗宝宝为**puppy**，这个时候假如有动物不知道该称如何呼狗宝宝，它需要查询一下。
```

2022-01-17 14:23 UTC, Sefank commented on book/contents/basic/trait/advance-trait.md
> +对于第二点，也很好理解，如果你在一个复杂类型的基础上，新引入一个泛型参数，可能需要修改很多地方，但是如果新引入的泛型参数有了默认类型，情况就会好很多。（这里想表达的可能是实现泛型的地方需要增加泛型类型？感觉讲得不是很清楚）
我个人觉得这里所谓的“需要修改很多地方”是指：添加泛型参数后，使用这个类型的代码需要逐个在类型提示部分添加泛型参数，就很麻烦；但是有了默认参数（且默认参数取之前的实现里假设的值的情况下）之后，原有的使用这个类型的代码就不需要做改动了。

2022-01-17 14:23 UTC, Sefank commented on book/contents/basic/trait/advance-trait.md
> +对于关联函数，其没有一个方法接收器( `receiver` )，故只会有其他参数的列表。**可以选择在任何函数或方法调用处使用完全限定语法**，但是，很多时候我们可以省略，因为 Rust 能够从程序中的其他信息中推导出这部分。只有当存在多个同名实现时，Rust 需要帮助以便知道我们希望调用哪个实现时，才需要使用这个较为冗长的语法。
嗯好像意思偏离了，这里给出Rust权威指南的翻译，仅供参考（原文没有分段，这里只是为了可读性分开了）：

> 对于关联函数而言，上面的形式会缺少receiver而只保留剩下的参数列表。**你可以在任何调用函数或方法的地方使用完全限定语法**，而Rust允许你忽略那些能够从其他上下文信息中推导出来的部分。
> 
> 只有当代码中存在多个同名实现，且Rust也无法区分出你期望调用哪个具体实现时，你才需要使用这种较为烦琐的显式语法。

2022-01-18 01:11 UTC, sunface commented on book/contents/basic/trait/advance-trait.md
> +对于第二点，也很好理解，如果你在一个复杂类型的基础上，新引入一个泛型参数，可能需要修改很多地方，但是如果新引入的泛型参数有了默认类型，情况就会好很多。（这里想表达的可能是实现泛型的地方需要增加泛型类型？感觉讲得不是很清楚）
是的，完全正确，兄弟你可以把这段理解合并到这段文字中，有助于读者更好的理解 :D

2022-01-18 01:16 UTC, sunface commented on book/contents/basic/trait/advance-trait.md
> +对于关联函数，其没有一个方法接收器( `receiver` )，故只会有其他参数的列表。**可以选择在任何函数或方法调用处使用完全限定语法**，但是，很多时候我们可以省略，因为 Rust 能够从程序中的其他信息中推导出这部分。只有当存在多个同名实现时，Rust 需要帮助以便知道我们希望调用哪个实现时，才需要使用这个较为冗长的语法。
这一段确实写得不好，需要重新润色下，感谢反馈

2022-01-18 01:26 UTC, Sefank requested changes
> 是的，完全正确，兄弟你可以把这段理解合并到这段文字中，有助于读者更好的理解 :D

这里提供修改的参考，有什么不对的地方欢迎指出哈~

2022-01-18 01:26 UTC, Sefank commented on book/contents/basic/trait/advance-trait.md
> +对于第二点，也很好理解，如果你在一个复杂类型的基础上，新引入一个泛型参数，可能需要修改很多地方，但是如果新引入的泛型参数有了默认类型，情况就会好很多。（这里想表达的可能是实现泛型的地方需要增加泛型类型？感觉讲得不是很清楚）
```suggestion
对于第二点，也很好理解：如果你在一个复杂类型的基础上，新引入一个泛型参数，那么对于每个使用这个类型的代码而言，当 Rust 不能推导出类型时，需要逐个在类型提示部分添加泛型参数；但是，如果新引入的泛型参数有了默认类型（且在默认参数取之前的实现里假设的值的情况下），原有的使用这个类型的代码就不需要做改动了。
```

2022-01-18 03:01 UTC, JesseAtSZ commented on book/contents/basic/trait/advance-trait.md
> +对于关联函数，其没有一个方法接收器( `receiver` )，故只会有其他参数的列表。**可以选择在任何函数或方法调用处使用完全限定语法**，但是，很多时候我们可以省略，因为 Rust 能够从程序中的其他信息中推导出这部分。只有当存在多个同名实现时，Rust 需要帮助以便知道我们希望调用哪个实现时，才需要使用这个较为冗长的语法。
我这里这样的写法可以吗？

2022-01-18 03:31 UTC, sunface commented on book/contents/basic/trait/advance-trait.md
> +对于关联函数，其没有一个方法接收器( `receiver` )，故只会有其他参数的列表。**可以选择在任何函数或方法调用处使用完全限定语法**，但是，很多时候我们可以省略，因为 Rust 能够从程序中的其他信息中推导出这部分。只有当存在多个同名实现时，Rust 需要帮助以便知道我们希望调用哪个实现时，才需要使用这个较为冗长的语法。
还不错，不过我合并后，需要再稍微润色下。

2022-01-18 03:32 UTC, sunface commented on book/contents/basic/trait/advance-trait.md
> +对于第二点，也很好理解，如果你在一个复杂类型的基础上，新引入一个泛型参数，可能需要修改很多地方，但是如果新引入的泛型参数有了默认类型，情况就会好很多。（这里想表达的可能是实现泛型的地方需要增加泛型类型？感觉讲得不是很清楚）
没毛病，完美

2022-01-18 04:54 UTC, sunface approved these changes

2022-01-18 04:54 UTC, merged

2022-01-18 05:08 UTC, sunface commented on book/contents/basic/trait/advance-trait.md
> +对于关联函数，其没有一个方法接收器( `receiver` )，故只会有其他参数的列表。**可以选择在任何函数或方法调用处使用完全限定语法**，但是，很多时候我们可以省略，因为 Rust 能够从程序中的其他信息中推导出这部分。只有当存在多个同名实现时，Rust 需要帮助以便知道我们希望调用哪个实现时，才需要使用这个较为冗长的语法。
完全限定语法可以用于任何函数或方法调用，那么我们为何很少用到这个语法？原因是Rust编译器能根据上下文帮我们自动推导出调用的路径，因此大多数时候，我们都无需使用完全限定语法。只有当存在多个同名函数或方法，且Rust无法区分出你想调用的目标函数时，该用法才能真正有用武之地。

最终修改如上