Update converse.md
sunface/rust-course pull request #231
Opened 2022-01-17 11:59 UTC by JesseAtSZ

2022-01-17 13:17 UTC, Sefank requested changes
提了一些小建议，有什么不对的地方欢迎指出 :D

2022-01-17 13:17 UTC, Sefank commented on book/contents/basic/converse.md
> +因为每个类型能表达的范围不一样，如果把大的类型转换成小的类型，会造成错误，因此我们需要把小的类型转换成大的类型，来避免这些问题的发生。
建议补充为
```
因为每个类型能表达的数据范围不同，如果把范围较大的类型转换成较小的类型，会造成错误，因此我们需要把范围较小的类型转换成较大的类型，来避免这些问题的发生。
```

2022-01-17 13:17 UTC, Sefank commented on book/contents/basic/converse.md
> +在一些场景中，使用 as` 关键字会有比较大的限制，如果你想要在类型转换上拥有完全的控制而不依赖内置的转换，例如处理转换错误，那么你将需要 `TryInto`：
这里行内代码误删了一个。此外，前后句是在描述两件事，我觉得用句号分割比较合适一些。
```
在一些场景中，使用 `as` 关键字会有比较大的限制。如果你想要在类型转换上拥有完全的控制而不依赖内置的转换，例如处理转换错误，那么可以使用 `TryInto`：
```

2022-01-17 13:17 UTC, Sefank commented on book/contents/basic/converse.md
> +在某些情况下，类型是可以进行隐式强制转换的，这些转换弱化了 Rust 的类型系统，它们的存在是为了让Rust在大多数场景可以工作(说白了，帮助用户省事)，而不是报各种类型上的编译错误。
逻辑好像不太对，是不是加一个“虽然”会好一点？
```
在某些情况下，类型是可以进行隐式强制转换的。虽然这些转换弱化了 Rust 的类型系统，但它们的存在是为了让 Rust 在大多数场景写得更顺手(说白了，帮助用户省事)，而不是报各种类型上的编译错误。
```

2022-01-17 13:17 UTC, Sefank commented on book/contents/basic/converse.md
> +`&i32`实现了特征`Trait`，`&mut i32`可以转换为`&i32`，但是`&mut i32`依然无法作为`Trait`来使用（这一段没读懂，代码中的例子好像和上面的文字描述关系不大）。
啊这个注释写在commit里或者用`<!-- 注释内容 -->`来写吧~

2022-01-17 13:21 UTC, Sefank requested changes
提了一些小建议，如果有什么不对的地方欢迎指出~

2022-01-17 13:45 UTC, JesseAtSZ commented
> 提了一些小建议，如果有什么不对的地方欢迎指出~

已修改，多谢

2022-01-17 13:48 UTC, Sefank commented on book/contents/basic/converse.md
> +`&i32`实现了特征`Trait`，`&mut i32`可以转换为`&i32`，但是`&mut i32`依然无法作为`Trait`来使用（这一段没读懂，代码中的例子好像和上面的文字描述关系不大）。
嗯我主要是怕会误导读者，不过现在这样其实也还行

2022-01-18 01:31 UTC, sunface commented on book/contents/basic/converse.md
> +`&i32`实现了特征`Trait`，`&mut i32`可以转换为`&i32`，但是`&mut i32`依然无法作为`Trait`来使用（这一段没读懂，代码中的例子好像和上面的文字描述关系不大）。
`Sefank`给的建议很中肯，不破坏原文会更好一些：)

2022-01-18 04:49 UTC, sunface approved these changes

2022-01-18 04:49 UTC, merged